name: fbz

version: 0.0.1-pre.0

homepage: https://github.com/PlugFox/FizzBuzzPsycho
repository: https://github.com/PlugFox/FizzBuzzPsycho
issue_tracker: https://github.com/PlugFox/FizzBuzzPsycho/issues
funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox
topics:
  - fizzbuzz
  - dart
  - algorithm
  - cli
  - benchmark

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  args: ^2.4.0
  ffi: ^2.1.0
  meta: ^1.10.0
  stack_trace: ^1.11.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
  benchmark_harness: ^2.2.2